theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true  
github:
  is_project_page: false
 
title: Improving Adversarial Waveform Generation based Singing Voice Conversion with Harmonic Signals
description:
  Haohan Guo<sup>1</sup>, Zhiping Zhou<sup>2</sup>,  Fanbo Meng<sup>2</sup>, Kai Liu<sup>2</sup> <br>
  <br>
  <sup>1</sup> The Chinese University of Hong Kong, Hong Kong SAR, China <br>
  <sup>2</sup> Sogou Inc., Beijing, China
