theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true  
github:
  is_project_page: false
 
title: Conversational End-to-End TTS for Voice Agents
description:
  Haohan Guo<sup>1</sup>, Shaofei Zhang<sup>2</sup>, Frank K. Soong<sup>2</sup>, Lei He<sup>2</sup>, Lei Xie<sup>1</sup> <br>
  <sup>1</sup>Audio, Speech and Language Processing Group (ASLP@NPU), School of Computer Science, Northwestern Polytechnical University, Xi’an, China <br>
  <sup>2</sup>Microsoft China
